version: '3.7'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - 

  wordpress:
    env_file:
      - ./.env