baseURL = "https://gda-cruz.42.fr/static"
defaultContentLanguage = "en"
languageCode = "en"

title = "Static Inception Page"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "index"
    url = "/about/"
    # Display name
    name = "About"
    # Weights are used to determine the ordering
    weight = 1
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/portugueseTorch"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  footer = "gda-cruz"
  description = "Random inspirational quote right here"
  avatarURL = "/images/torch.webp"